formated output to multiqc json
eastgenomics/eggd_sex_check pull request #2
Opened 2024-02-21 15:39 UTC by pofuoku

Reordered sex_check results columns
Included custom mqc config
Change file format to json

Example of completed job https://platform.dnanexus.com/panx/projects/Gfx24204p0Z3Xp99bZQG94jq/monitor/job/GgF18Bj4p0Z1BxQxBgpxXKPx 

@kjwinfield

2024-02-21 15:39 UTC, pep8speaks commented
Hello @pofuoku! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/sex_check.py`](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py):

> [Line 156:40](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L156): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 156:80](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L156): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 181:17](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L181): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 182:17](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L182): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 183:17](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L183): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 190:17](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L190): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 195:80](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L195): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 197:17](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L197): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

2024-02-21 16:21 UTC, kjwinfield requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2)* status: all files reviewed, 2 unresolved discussions (waiting on @pofuoku)

___
*[`src/sex_check.py` line 156 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2#-NrBR3KT-07tyc0JlcNe:-NrBR3KT-07tyc0JlcNf:bvd1yye) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L156)):*
> ```Python
>     data = {
>         bam_file_prefix: {
>             "matched": str(reported_sex==predicted_sex) if reported_sex != "N" else "NA",
> ```

could you put this if/else statement outside the dict and then refer to the outcome of the if/else statement in the dict
line's too long for pep8 anyway + this will make it easier to read :)
___
*[`src/sex_check.py` line 195 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2#-NrBRYMzAJSUIrYiXfqc:-NrBRYMzAJSUIrYiXfqd:br18r3y) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L195)):*
> ```Python
>             "predicted_sex": {
>                 "title": "Predicted Sex",
>                 "description": "Sex infered from number of mapped reads to ChrY",
> ```

typo should say "inferred"
also pep8 has this line being too long, could rephrase or put on multiple lines


<!-- Sent from Reviewable.io -->

2024-02-22 09:51 UTC, pofuoku reviewed
Completed job with updated app
https://platform.dnanexus.com/panx/projects/Gfx24204p0Z3Xp99bZQG94jq/monitor/job/GgFVP9Q4p0Z3YG3JP0f6FPp4

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2#-:-NrFD66i-cznPiA7mZgL:b-h91kiq)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`src/sex_check.py` line 156 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2#-NrBR3KT-07tyc0JlcNe:-NrFCzupAAbjl7-e3kWi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/e55925372b21e25fe10149f3e3ccd54134a0544e/src/sex_check.py#L156)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you put this if/else statement outside the dict and then refer to the outcome of the if/else statement in the dict
line's too long for pep8 anyway + this will make it easier to read :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-22 10:31 UTC, kjwinfield approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pofuoku)



<!-- Sent from Reviewable.io -->

2024-02-22 10:31 UTC, merged